### ISSUE TITLE
Adicionar suporte ao Sentry

### ISSUE THREAD

**Issue by pythrick** [pythrick/drf-cookiecutter#19]

**Comment by Cassianosricardo** [comment]
Nice! Pensei nisso tb

**Comment by Cassianosricardo** [comment]
Só que isso tem o drawback de ter de criar o projeto no sentry antes mesmo dele começar... Pode impedir o uso de quem não quer usar o sentry. O Cookie cutter permite que usemos condicionais pra popular ou não templates?

**Comment by Cassianosricardo** [comment]
https://cookiecutter.readthedocs.io/en/1.7.2/advanced/choice_variables.html
