### ISSUE TITLE
Error starting API

### ISSUE THREAD

**Issue by lucassempre** [pythrick/drf-cookiecutter#24]
Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
web_1  |     import psycopg2 as Database
web_1  | ModuleNotFoundError: No module named 'psycopg2'
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
web_1  |     mod = importlib.import_module(module)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/app/super_pizzaria/wsgi.py", line 16, in <module>
web_1  |     application = get_wsgi_application()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web_1  |     django.setup(set_prefix=False)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
web_1  |     app_config.import_models()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
web_1  |     self.models_module = import_module(models_module_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 2, in <module>
web_1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
web_1  |     class AbstractBaseUser(models.Model):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
web_1  |     new_class.add_to_class('_meta', Options(meta, app_label))
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
web_1  |     value.contribute_to_class(cls, name)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
web_1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
web_1  |     return getattr(connections[DEFAULT_DB_ALIAS], item)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
web_1  |     backend = load_backend(db['ENGINE'])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
web_1  |     return import_module('%s.base' % backend_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
web_1  |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
web_1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
web_1  | [2020-10-09 22:22:07 +0000] [7] [INFO] Worker exiting (pid: 7)
web_1  | [2020-10-09 22:22:07 +0000] [10] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
web_1  |     import psycopg2 as Database
web_1  | ModuleNotFoundError: No module named 'psycopg2'
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
web_1  |     mod = importlib.import_module(module)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/app/super_pizzaria/wsgi.py", line 16, in <module>
web_1  |     application = get_wsgi_application()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web_1  |     django.setup(set_prefix=False)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
web_1  |     app_config.import_models()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
web_1  |     self.models_module = import_module(models_module_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 2, in <module>
web_1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
web_1  |     class AbstractBaseUser(models.Model):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
web_1  |     new_class.add_to_class('_meta', Options(meta, app_label))
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
web_1  |     value.contribute_to_class(cls, name)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
web_1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
web_1  |     return getattr(connections[DEFAULT_DB_ALIAS], item)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
web_1  |     backend = load_backend(db['ENGINE'])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
web_1  |     return import_module('%s.base' % backend_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
web_1  |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
web_1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
web_1  | [2020-10-09 22:22:07 +0000] [10] [INFO] Worker exiting (pid: 10)
web_1  | [2020-10-09 22:22:07 +0000] [8] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
web_1  |     import psycopg2 as Database
web_1  | ModuleNotFoundError: No module named 'psycopg2'
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
web_1  |     mod = importlib.import_module(module)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/app/super_pizzaria/wsgi.py", line 16, in <module>
web_1  |     application = get_wsgi_application()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web_1  |     django.setup(set_prefix=False)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
web_1  |     app_config.import_models()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
web_1  |     self.models_module = import_module(models_module_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 2, in <module>
web_1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
web_1  |     class AbstractBaseUser(models.Model):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
web_1  |     new_class.add_to_class('_meta', Options(meta, app_label))
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
web_1  |     value.contribute_to_class(cls, name)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
web_1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
web_1  |     return getattr(connections[DEFAULT_DB_ALIAS], item)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
web_1  |     backend = load_backend(db['ENGINE'])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
web_1  |     return import_module('%s.base' % backend_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
web_1  |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
web_1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
web_1  | [2020-10-09 22:22:07 +0000] [8] [INFO] Worker exiting (pid: 8)
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
web_1  |     self.sleep()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
web_1  |     ready = select.select([self.PIPE[0]], [], [], 1.0)
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
web_1  |     self.reap_workers()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
web_1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
web_1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/bin/gunicorn", line 8, in <module>
web_1  |     sys.exit(run())
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
web_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 228, in run
web_1  |     super().run()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
web_1  |     Arbiter(self).run()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
web_1  |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
web_1  |     self.stop()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
web_1  |     time.sleep(0.1)
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
web_1  |     self.reap_workers()
web_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
web_1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
web_1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
super_pizzaria_web_1 exited with code 1

**Comment by RANA-ATI** [comment]
@lucassempre Did you find the solution ?
