### ISSUE TITLE
Adicionar .secrets.template.yaml com as credenciais do banco de dados

### ISSUE THREAD

**Issue by pythrick** [pythrick/drf-cookiecutter#3]
- [x] Adicionar `.secrets.template.yaml` com as credenciais do banco de dados
- [x] Mudar `.secrets.*` para `.secrets.yaml` no `.gitignore`
- [x] Implementar método `copy_dot_secrets()` no hook `post_gen_project.py`

**Comment by fghisi** [comment]
Eu vou nessa!
